Repository SE-TINF22B6/CookHub, pull requests merged in 2024-04, with the labels that each got.

#101 Recipe elements position fix
  Frontend/src/assets/newRecipe/Cook_Pot.png
  Frontend/src/assets/newRecipe/Cook_Pot_Cover.png
  Frontend/src/assets/newRecipe/Knife_Cartoon.png
  Frontend/src/components/FormPropsTextFields.tsx
  Frontend/src/components/Slider.tsx
  Frontend/src/pages/FoodForge.tsx
  Frontend/src/pages/MyRecipes.tsx
  Frontend/src/pages/Profile.tsx
  Frontend/src/style/FoodForge.css
  Frontend/src/style/MyRecipes.css
  Frontend/src/style/Profile.css
Labels: bug, task, Just SoftwareEngineering

#136 MyRecipes: Replaced Card Background without Postit and integrated Logo
  Frontend/src/assets/fillElements/Favorite (1).png
  Frontend/src/assets/fillElements/GreenCard256.png
  Frontend/src/assets/fillElements/InfoCard_Background.png
  Frontend/src/assets/fillElements/Info_Card_Logo.png
  Frontend/src/assets/fillElements/istockphoto-1470084374-1024x1024.png
  Frontend/src/assets/fillElements/istockphoto-836336588-612x612.png
  Frontend/src/assets/fillElements/zufgiujho.png
  Frontend/src/pages/MyRecipes.tsx
  Frontend/src/style/MyRecipes.css
Labels: bug, task

#150 // MyRecipes
  Frontend/src/pages/MyRecipes.tsx
  Frontend/src/style/MyRecipes.css
Labels: task

#155 Frontend: MyRecipes: added like button to myrecipe page
  Frontend/src/pages/MyRecipes.tsx
Labels: task, Just SoftwareEngineering
