Repository SE-TINF22B6/CookHub, pull requests merged in 2024-05, with the labels that each got.

#157 Frontend: FoodForge: Replacing Slider with RadioGroup & Structure adjustments
  Frontend/src/components/DifficultyRadioGroup.tsx
  Frontend/src/components/FormPropsTextFields.tsx
  Frontend/src/components/Slider.tsx
  Frontend/src/pages/FoodForge.tsx
  Frontend/src/style/FoodForge.css
Labels: enhancement, task

#172 // MyRecipes.tsx
  Frontend/src/assets/fillElements/rageQuit-btn.png
  Frontend/src/pages/MyRecipes.tsx
  Frontend/src/style/MyRecipes.css
Labels: enhancement, task

#179 // Finalized API Prompt
  Backend/Services/AdventurizeService.cs
Labels: enhancement

#178 // Frontend: created SignUp page
  Frontend/src/App.tsx
  Frontend/src/pages/MyRecipes.tsx
  Frontend/src/pages/SignUp.tsx
  Frontend/src/style/SignUp.css
Labels: enhancement, task

#186 // FoodForge
  Frontend/src/components/AddIngredientApp.tsx
  Frontend/src/components/Ingredient.tsx
  Frontend/src/components/IngredientInput.tsx
  Frontend/src/components/IngredientList.tsx
  Frontend/src/components/types.tsx
  Frontend/src/pages/FoodForge.tsx
Labels: enhancement

#190 // Settings
  Frontend/src/pages/MyRecipes.tsx
  Frontend/src/pages/Settings.tsx
  Frontend/src/style/ImageUploader.css
  Frontend/src/style/Settings.css
Labels: enhancement

#194 // Profile
  Frontend/src/App.tsx
  Frontend/src/pages/PleaseLogin.tsx
  Frontend/src/pages/Profile.tsx
  Frontend/src/style/Profile.css
Labels: enhancement, task

#198 //Carlos_PopUp
  Frontend/src/helpers/Carlos_PopUp.tsx
  Frontend/src/pages/AboutUs.tsx
  Frontend/src/pages/SignUp.tsx
  Frontend/src/style/Carlos_PopUp.css
Labels: enhancement, task

#207 //FoodForge
  Frontend/src/assets/recipes/photo_placeholder.png
  Frontend/src/components/DifficultyRadioGroup.tsx
  Frontend/src/components/ImageUploader.tsx
  Frontend/src/pages/FoodForge.tsx
  Frontend/src/style/FoodForge.css
  Frontend/src/style/ImageUploader.css
Labels: enhancement

#212 Frontend: LoginPage: Fix
  Frontend/src/components/CreateRecipeBlank.tsx
  Frontend/src/components/DifficultyRadioGroup.tsx
  Frontend/src/components/FormPropsTextFields.tsx
  Frontend/src/helpers/Carlos_PopUp.tsx
  Frontend/src/pages/FoodForge.tsx
  Frontend/src/pages/Login.tsx
  Frontend/src/style/DifficultyRadioGroup.css
  Frontend/src/style/FoodForge.css
  Frontend/src/style/Login.css
Labels: bug, enhancement

#214 Testing: Selenium: Setup
  package-lock.json
  package.json
Labels: documentation, task, TEST

#217 Backend: Make adventure text savable
  Backend/API/Controllers/RecipeController.cs
  Backend/API/Models/AdventureModel.cs
  Backend/Services/RecipeService.cs
  Backend/Tests/ApiTests/RecipeControllerTests.cs
Labels: task

#237 //LandingPage
  Frontend/src/pages/Welcome.tsx
  Frontend/src/style/Welcome.css
Labels: enhancement, task

#241 Frontend: LoginPage: responsification & NavBar: small bugfix
  Frontend/src/pages/Login.tsx
  Frontend/src/style/Login.css
  Frontend/src/style/NavBar.css
Labels: bug, enhancement, task

#248 Frontend: fix recipes not showing in https
  Frontend/src/pages/FindRecipes.tsx
Labels: bug

#253 // Frontend: FindRecipe: 1/2 responsificated
  Frontend/src/App.tsx
  Frontend/src/components/NavBar.tsx
  Frontend/src/pages/FindRecipes.tsx
  Frontend/src/style/FindRecipes.css
Labels: enhancement, task

#270 // FindRecipe
  Frontend/src/pages/FindRecipes.tsx
  Frontend/src/style/FindRecipes.css
Labels: enhancement, task

#273 // MyRecipes
  Frontend/src/pages/MyRecipes.tsx
  Frontend/src/style/MyRecipeLoggedIn.css
  Frontend/src/style/MyRecipes.css
Labels: enhancement, task
